

void hadware_setup();

/*
ECG sensor. The electrical signal generated by the heart muscles during contraction can be detected using an
ECG sensor.
*/
float read_heart_beat_in_millivolts(); //1x

/*
Blood Volume Pulse (BVP) sensor. Also known as a Photoplethysmography (PPG) sensor, it emits light into the tissue and measures
the reflected light. The amount of observed reflected light varies according to the blood flowing through the vessels,
thus serving as a measure for cardiac activity.
*/
float read_blood_volume_pulse_in_percentage(); //1x

/*
Galvanic Skin Response (GSR) sensor. Also known as Electrodermal Activity (EDA) sensor, it measures the variation in electrical
conductance resulting from sweat released by the glands on the skin. Since these glands are regulated by the sympathetic
nervous system, changes in electric conductance serve as a good indicator of physiological arousal.
*/
float read_galvanic_skin_response_in_microsecond(); //1x

/*
Respiration sensor. The expansion and contraction of the chest cavity can be measured using a Hall effect sensor.
*/
float read_respiration_sensor_in_percentage();

/*
    Duty Cycle deve ser um valor entre 0 até 1,
    onde no caso do atmega328P será convertido em um valor inteiro
    entre o até 255
*/
void write_amusing_led(float duty_cycle);
void write_boring_led(float duty_cycle);
void write_relaxing_led(float duty_cycle);
void write_scary_led(float duty_cycle);
void write_undefined_led(float duty_cycle);

/*
    Uma vez que o Arduino Uno não é possível de fazer 9 leituras analógicas então foi escolhido os 4 primeiros sensores.
    e desabilitado as outras leituras.
*/

/*
Skin temperature sensor. Small variations in skin temperature were measured and converted to electrical signals
using an epoxy rod thermistor.
*/
//float read_skin_temperature_in_celsius();

/*
EMG sensors. The surface voltage associated with muscle contractions can be measured using a
surface-Electromyography (sEMG, simply EMG) sensor. Previous research in AC has generally focused on three
muscles. These are the zygomaticus major and the corrugator supercilii muscle groups on the face, and the trapezius muscle on the upper-back.
Accordingly, a total of three EMG sensors (one each for the aforementionedmuscles) were used for this experiment.
The skin at the placement sites for these sensors was prepared by gently abrading it using the Nuprep cream. The details on the placement
of the pre-gelled electrodes for these sensors are as follows:

    1. zygomaticus major – The first electrode was fixed midway along an imaginary line joining the cheilion and
    the preauricular depression, i.e., at the bony dimple above the posterior edge of the zygomatic arch. The
    second electrode was placed 1 cm inferior and medial to the first, i.e., approximately at the point where the
    horizontal sub-nasale line first intersects the zygomaticus major muscle. The third electrode serves as a ref-
    erence electrode and was placed at the left/right upper edge of the forehead, i.e., ~1 cm below the hairline.
    
    2. corrugator supercilii – The first electrode (surface area: ~6 cm2) was fixed above the brow on an imaginary
    vertical line that extends over the endocanthion (i.e., the point at which the inner ends of the upper and
    lower eyelid meet). The second electrode was placed 2 cm to the right and slightly superior the first elec-
    trode such that it sits at the upper edge of the eyebrow. The third electrode serves as a reference electrode
    and was placed at the central upper end of the forehead, i.e., ~2 cm below the hairline.
    
    3. trapezius – A triode electrode (surface area: ~30 cm2) was placed at the edge between superior and middle
    fibres of the trapezius muscle, approximately 10 cm left/right from the first thoracic vertebra for a 180 cm
    tall adult.
*/

// typedef enum MuscleSensorType
// {
//     ZYGOMATICUS,
//     SUPERCILII,
//     TRAPEZIUS
// } MuscleSensorType;

// float read_muscle_sensor_in_microcoulomb(int type);

/*
Joystick. The joystick was the only instrument in the experiment that is directly controlled by the participants.
The used joystick is a generic digital gaming peripheral that features a return spring. This provided the user proprioceptive
feedback about the location of the pointer in the interface, thereby helping to mitigate the cognitive
load associated with simultaneous tasks of watching the video and annotating the emotional experience.
*/
// float read_joytick(); //